// const error = new Error("Something went wrong")
// console.log(error.stack);
// console.log(error.message);
// throw new Error("Hello This is errrorr")
// const {CustomError} = require("./CustomError")
// throw new CustomError("My Custom error hereee")

const doSomething=()=>{
    // fetch("localhost/3000")
    console.log("form errorr");
    const data = "mubashirrr"
    return data
}


// try {
//     doSomething()
// } catch (error) {
//     console.log("Something Went wrong");
//     console.log(error);
    
// }

// const promise = new Promise((resolve,reject)=>{
//     if(true){
//         resolve(doSomething());
//     }
//     else{
//         reject(doSomething())
//     }
// })

// promise.then((val)=> {console.log(val)})
//     .catch((error)=>{
//         console.log("error occured");
//         console.log(error);
//     })


